### ISSUE TITLE
atoi usage

### ISSUE THREAD

**Issue by CameronNemo** [glats/kbdlight#1]
https://github.com/glats/kbdlight/blob/e00db0e911f42338d9fd9fde299e4b8958f87216/src/lib/file.c#L18

atoi usage is often discouraged, as it is impossible to perform any error checking. How does your program behave when the brightness file contains garbage (e.g. `dfoijs8393`)? Or if the file is empty?

>    The atoi() function is subsumed by strtol() but is retained because it is used extensively in existing code. If the number is not known to be in range, strtol() should be used because atoi() is not required to perform any error checking.

https://pubs.opengroup.org/onlinepubs/9699919799/functions/atoi.html

**Comment by glats** [comment]
Hi! Thanks for your review!
Well I understand your point and the current file is a single number value.
The file is provided by the kernel and as far I know always will be in that way. However if you have a better idea please let me know.

**Comment by glats** [comment]
Reading a little be more it seems that aoti is deprecated. I think I'll use strtol instead.

**Comment by glats** [comment]
Changed!
